
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebDAL
{

using System;
    using System.Collections.Generic;
    
public partial class auditentry
{

    public int auditEntryID { get; set; }

    public int userID { get; set; }

    public string auditEntryOwnerType { get; set; }

    public string auditEntryOwnerTypeID { get; set; }

    public string auditEntrySummary { get; set; }

    public string auditEntryDetail { get; set; }

    public string auditEntryComment { get; set; }

    public System.DateTime auditEntryTime { get; set; }



    public virtual user user { get; set; }

}

}
