//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class authenticationtoken
    {
        public System.Guid authenticationTokenValue { get; set; }
        public int userID { get; set; }
        public string ipAddress { get; set; }
        public System.DateTime issueDate { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
    
        public virtual user user { get; set; }
    }
}
