
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebDAL
{

using System;
    using System.Collections.Generic;
    
public partial class route
{

    public route()
    {

        this.coords = new HashSet<coord>();

    }


    public int routeID { get; set; }

    public int timeTrackingID { get; set; }

    public System.DateTime startTime { get; set; }

    public Nullable<System.DateTime> endTime { get; set; }

    public Nullable<decimal> clockInLat { get; set; }

    public Nullable<decimal> clockInLng { get; set; }



    public virtual ICollection<coord> coords { get; set; }

    public virtual timetracking timetracking { get; set; }

}

}
