
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebDAL
{

using System;
    using System.Collections.Generic;
    
public partial class user
{

    public user()
    {

        this.auditentries = new HashSet<auditentry>();

        this.authenticationtokens = new HashSet<authenticationtoken>();

        this.messages = new HashSet<message>();

        this.timetrackings = new HashSet<timetracking>();

        this.userabsences = new HashSet<userabsence>();

        this.userconversations = new HashSet<userconversation>();

        this.usermessagereceipts = new HashSet<usermessagereceipt>();

        this.userrolemappings = new HashSet<userrolemapping>();

        this.userabsencebalances = new HashSet<userabsencebalance>();

    }


    public int userID { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string passwordSalt { get; set; }

    public string title { get; set; }

    public string firstname { get; set; }

    public string surname { get; set; }

    public string employerNumber { get; set; }

    public string identificationNumber { get; set; }

    public string deviceID { get; set; }

    public string emailAddress { get; set; }

    public string cellNumber { get; set; }

    public bool isApproved { get; set; }

    public string isLockedOut { get; set; }

    public Nullable<System.DateTime> lastActivityDate { get; set; }

    public Nullable<System.DateTime> lastPasswordChange { get; set; }

    public Nullable<System.DateTime> lastLoginDate { get; set; }

    public Nullable<int> failedPasswordAttemptCount { get; set; }

    public System.DateTime created { get; set; }

    public Nullable<System.DateTime> updated { get; set; }

    public int companyID { get; set; }



    public virtual ICollection<auditentry> auditentries { get; set; }

    public virtual ICollection<authenticationtoken> authenticationtokens { get; set; }

    public virtual ICollection<message> messages { get; set; }

    public virtual ICollection<timetracking> timetrackings { get; set; }

    public virtual ICollection<userabsence> userabsences { get; set; }

    public virtual ICollection<userconversation> userconversations { get; set; }

    public virtual ICollection<usermessagereceipt> usermessagereceipts { get; set; }

    public virtual ICollection<userrolemapping> userrolemappings { get; set; }

    public virtual company company { get; set; }

    public virtual ICollection<userabsencebalance> userabsencebalances { get; set; }

}

}
