
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class group
{

    public int groupID { get; set; }

    public string groupCode { get; set; }

    public string groupName { get; set; }

    public string groupDescription { get; set; }

    public string groupStatus { get; set; }

}

}
