
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class message
{

    public message()
    {

        this.usermessagereceipts = new HashSet<usermessagereceipt>();

    }


    public int messageID { get; set; }

    public int userID { get; set; }

    public int conversationID { get; set; }

    public string messageText { get; set; }

    public System.DateTime dateSent { get; set; }



    public virtual conversation conversation { get; set; }

    public virtual ICollection<usermessagereceipt> usermessagereceipts { get; set; }

    public virtual user user { get; set; }

}

}
