//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetracking
    {
        public timetracking()
        {
            this.routes = new HashSet<route>();
        }
    
        public int timeTrackingID { get; set; }
        public int userID { get; set; }
        public System.DateTime clockInTime { get; set; }
        public Nullable<System.DateTime> clockOutTime { get; set; }
        public Nullable<decimal> clockInLat { get; set; }
        public Nullable<decimal> clockInLng { get; set; }
        public Nullable<decimal> clockOutLat { get; set; }
        public Nullable<decimal> clockOutLng { get; set; }
    
        public virtual ICollection<route> routes { get; set; }
        public virtual user user { get; set; }
    }
}
