
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class usermessagereceipt
{

    public int userMessageReceiptID { get; set; }

    public int messageID { get; set; }

    public int userID { get; set; }

    public Nullable<bool> hasReceived { get; set; }



    public virtual message message { get; set; }

    public virtual user user { get; set; }

}

}
