
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class userconversation
{

    public int userConversationID { get; set; }

    public int conversationID { get; set; }

    public int userID { get; set; }

    public bool isHidden { get; set; }



    public virtual conversation conversation { get; set; }

    public virtual user user { get; set; }

}

}
